### PR TITLE
Catch import errors in __init__.py

### PR DESCRIPTION
**Pull request by tilgovi**
The package module can catch import errors, allowing the module
to be imported by the setup script without having boto installed.

This allows `pip install ansible-ec2-inventory` to succeed without
having boto installed beforehand.

### CODE REVIEW

**Comment by andrenarchy** [comment]
Doesn't `pip install ansible-ec2-inventory` also install `boto`?

**Comment by tilgovi** [comment]
If you point pip at the requirements file directly, you get boto.

If you try to install from pypi, pip has to read setup.py, which tries to import the version, which tries to import boto before pip even knows boto is required.

This patch is ugly though, and I'm sorry. I should have just opened an issue but I wanted to explain with code where things fail.

See here: http://stackoverflow.com/questions/17583443/what-is-the-correct-way-to-share-package-version-with-setup-py-and-the-package

We should probably just read the file in setup.py instead of importing it, but have a look at those solutions.

**Comment by andrenarchy** [comment]
Thanks for sharing this! @tilgovi Do you want to open a PR for this?

**Comment by andrenarchy** [comment]
This is fixed in 0.1.8.

**Comment by tilgovi** [comment]
Sorry I never responded. I've been busy and wanted to follow up, but hadn't had a chance. Thanks!

**Comment by andrenarchy** [comment]
No worries! :)

**Pull request closed without merging**
